[workspace]
resolver = "3"
members = ["crates/rbpmn-core", "crates/rbpmn-engine", "crates/rbpmn-model", "crates/rbpmn-server", "crates/rbpmn-wasm"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.91"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
roxmltree = "0.20"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
