// Builds the two UI bundles into crates/rbpmn-ui/assets/, which Rust inlines
// into self-contained documents at render time.
//
// The output is gitignored, like every other generated artifact in this repo.
// `cargo build` of rbpmn-ui therefore needs this to have run once, and its
// build.rs says exactly that when it hasn't — node and wasm-pack are already
// prerequisites for `just playground` and `just parity`, so this adds a
// bootstrap step rather than a new tool.
//
// The editor additionally inlines the WASM linter as base64: it is a document
// that must work from file://, so it cannot fetch a sidecar .wasm. The
// inspector deliberately does *not* carry the linter — it renders a model
// that already deployed, and half a megabyte of validator would be dead
// weight in a document that gets emailed around.

import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const uiRoot = join(here, '..');
const repoRoot = join(uiRoot, '..');
const assets = join(repoRoot, 'crates', 'rbpmn-ui', 'assets');

const only = process.argv.find((a) => a.startsWith('--only='))?.slice('--only='.length);
const entries = only ? [only] : ['inspector', 'editor'];

function run(cmd, args, cwd = uiRoot, env = {}) {
  execFileSync(cmd, args, { cwd, stdio: 'inherit', env: { ...process.env, ...env } });
}

/// wasm-pack's web target, re-emitted as an ES module holding the bytes so
/// the editor can be one file. `initSync` is not an option: Chrome refuses
/// synchronous compilation of buffers over 4KB on the main thread, so the
/// glue's async init gets the bytes instead.
function generateWasmInline() {
  const out = join(uiRoot, 'wasm');
  // `--features dmn`: the editor validates a bundle's decisions, so its
  // module carries the DMN validator. Named explicitly although it is the
  // default, because `just parity` builds the native side the same way — the
  // two must be the same build, and a mismatch fails per fixture rather than
  // silently.
  run('wasm-pack', [
    'build',
    join(repoRoot, 'crates', 'rbpmn-wasm'),
    '--target',
    'web',
    '--out-dir',
    out,
    '--no-typescript',
    '--features',
    'dmn',
  ]);
  const bytes = readFileSync(join(out, 'rbpmn_wasm_bg.wasm'));
  const generated = join(uiRoot, 'src', 'generated');
  mkdirSync(generated, { recursive: true });
  writeFileSync(
    join(generated, 'wasm-inline.js'),
    `// GENERATED by ui/scripts/build.mjs — do not edit.\n` +
      `export const WASM_BASE64 = '${bytes.toString('base64')}';\n`
  );
  console.log(`inlined ${(bytes.length / 1024).toFixed(0)} KiB of WASM`);
}

mkdirSync(assets, { recursive: true });

for (const entry of entries) {
  if (!['inspector', 'editor'].includes(entry)) {
    throw new Error(`unknown entry '${entry}' (inspector|editor)`);
  }
  if (entry === 'editor') generateWasmInline();

  console.log(`\n--- building ${entry}`);
  run('npx', ['vite', 'build'], uiRoot, { RBPMN_UI_ENTRY: entry });

  const dist = join(uiRoot, 'dist', entry);
  const js = readFileSync(join(dist, `${entry}.js`), 'utf8');
  const cssPath = join(dist, `${entry}.css`);
  const css = existsSync(cssPath) ? readFileSync(cssPath, 'utf8') : '';

  writeFileSync(join(assets, `${entry}.js`), js);
  writeFileSync(join(assets, `${entry}.css`), css);
  console.log(
    `${entry}: ${(js.length / 1024).toFixed(0)} KiB js + ${(css.length / 1024).toFixed(0)} KiB css` +
      ` -> crates/rbpmn-ui/assets/`
  );
  rmSync(dist, { recursive: true, force: true });
}
